name: Libra Lip Website Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: github.repository == 'libra/lip'
    
    runs-on: ubuntu-latest

    steps:
    # Checks-out the Libra lip repository under $GITHUB_WORKSPACE, so job can access it
    - uses: actions/checkout@v2
    # Installs node and yarn
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    # Install git
    - name: Install git
      run: |
        sudo apt --assume-yes update
        sudo apt --assume-yes install git
    # Deploy the website (site based on Docusaurus v2)
    - name: Deploying Libra Lip Website to GitHub Pages
      run: |
        git config --global user.email "libra-doc-bot@users.noreply.github.com"
        git config --global user.name "Libra Lip Website Deployment Script"
        echo "machine github.com login libra-doc-bot password ${{ secrets.PUBLISH_AND_DEPLOY_TOKEN }}" > ~/.netrc
        GIT_USER=libra-doc-bot USE_SSH=false yarn deploy
